<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(DefineConstants);WINDOWS</DefineConstants>
    <AllowUnsafeBlocks Condition="$([MSBuild]::IsOSPlatform('Windows'))">true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="fat32format.exe" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="SharpCompress" Version="0.39.0" />
    <PackageReference Include="Spectre.Console" Version="0.49.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BadBuilder.Formatter\BadBuilder.Formatter.csproj" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
  </ItemGroup>

</Project>
